DEF_CMD("in", IN_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	IN(0)
	PUSH(0)
})

DEF_CMD("out", OUT_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	OUT(0)
})

DEF_CMD("sqrt", SQRT_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	SQRT(0)
	PUSH(0)
})

DEF_CMD("mul", MUL_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	GET(1, 2)
	MUL(0, 1)
	PUSH(0)
})

DEF_CMD("div", DIV_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	GET(1, 2)
	DIV(1, 0)
	PUSH(1)
})

DEF_CMD("add", ADD_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	GET(1, 2)
	ADD(0, 1)
	PUSH(0)
})

DEF_CMD("sub", SUB_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	GET(1, 2)
	SUB(1, 0)
	PUSH(1)
})

DEF_CMD("push", PUSH_REG_CMD, ONE_ARG_REG_OR_RAM_SIZE, ONE_ARG, REGISTER, NOT_JUMP,
{

	TAKE(0, REGISTER)
	PUSH(0) 
})

DEF_CMD("push", PUSH_DIG_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, DIGIT, NOT_JUMP,
{

	TAKE(0, DIGIT)
	PUSH(0)
})

DEF_CMD("pop", POP_CMD, ONE_ARG_REG_OR_RAM_SIZE, ONE_ARG, REGISTER, NOT_JUMP,
{

	GET(0, 1)
	POP
	TAKE(1, REGISTER_NUM)
	SET(1, 0, REGISTER)
})

DEF_CMD("jmp", JMP_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMP
})

DEF_CMD("jb", JB_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(<)
})

DEF_CMD("jbe", JBE_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(<=)	
})

DEF_CMD("je", JE_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(==)
})

DEF_CMD("jne", JNE_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(!=)
})

DEF_CMD("ja", JA_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(>)
})

DEF_CMD("jae", JAE_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	JMPC(>=)
})

DEF_CMD("jm", JM_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	long long jump_byte = *(long long*)(buf_byte_code + cur_byte + 1);

	time_t bad_time = 0;
	time(&bad_time);
	char *time = asctime(localtime(&bad_time));
	time[3] = '\0';

	if (strequ(time, "Mon"))
		cur_byte = jump_byte;
	else
		cur_byte += ONE_ARG_DIGIT_OR_LABEL_SIZE;
})

DEF_CMD("call", CALL_CMD, ONE_ARG_DIGIT_OR_LABEL_SIZE, ONE_ARG, LABEL, JUMP,
{

	PUSHR
	JMP
})

DEF_CMD("ret", RET_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, JUMP,
{

	JMPR
	POPR
})

DEF_CMD("hlt", HLT_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, JUMP,
{

	HLT
})

DEF_CMD("cmp", CMP_CMD, ZERO_ARG_SIZE, ZERO_ARG, VOID_ARG, NOT_JUMP,
{

	GET(0, 1)
	GET(1, 2)
	SET(1, 0, CMP_RES)
})

DEF_CMD("push", PUSH_RAM_CMD, ONE_ARG_REG_OR_RAM_SIZE, ONE_ARG, RAM, NOT_JUMP, 
{

	TAKE(0, RAM)
	PUSH(0)
})

DEF_CMD("pop", POP_RAM_CMD, ONE_ARG_REG_OR_RAM_SIZE, ONE_ARG, RAM, NOT_JUMP,
{

	GET(0, 1)
	POP
	TAKE(1, RAM_NUM)
	SET(1, 0, RAM)
})
	
